kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{ include "trust-manager-csi-driver.labels" . | nindent 4 }}
  name: {{ include "trust-manager-csi-driver.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "trust-manager-csi-driver.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "trust-manager-csi-driver.name" . }}
  namespace: {{ .Release.Namespace }}