apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.app.driver.name }}
  labels:
    {{ include "trust-manager-csi-driver.labels" . | nindent 4 }}
spec:
  podInfoOnMount: true
  volumeLifecycleModes:
  - Ephemeral